// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7wWxFANAWzhvOFZQU07fwgxnXKiPAm3g',
    appId: '1:546833268338:web:56f53a0fbb9b127a440ceb',
    messagingSenderId: '546833268338',
    projectId: 'whatsmy-app',
    authDomain: 'whatsmy-app.firebaseapp.com',
    storageBucket: 'whatsmy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7jUXs9r9wEvkdOuANq3rozFUFm8P2hE',
    appId: '1:546833268338:android:103b059336c3cee4440ceb',
    messagingSenderId: '546833268338',
    projectId: 'whatsmy-app',
    storageBucket: 'whatsmy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRvmXNv2gtOxJ78KlRrIsScJuIchKTjTg',
    appId: '1:546833268338:ios:113dbd80d1217c08440ceb',
    messagingSenderId: '546833268338',
    projectId: 'whatsmy-app',
    storageBucket: 'whatsmy-app.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRvmXNv2gtOxJ78KlRrIsScJuIchKTjTg',
    appId: '1:546833268338:ios:113dbd80d1217c08440ceb',
    messagingSenderId: '546833268338',
    projectId: 'whatsmy-app',
    storageBucket: 'whatsmy-app.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
